#!/bin/bash

echo "Installed package versions:"

echo "java: $(java -version 2>&1 | awk -F '"' '/version/ {print $2}')"
echo "maven: $(mvn -version 2>&1 | awk '/Apache Maven/ {print $3}')"
echo "node: $(node -v)"
echo "npm: $(npm -v)"
echo "yarn: $(yarn -v)"
echo "bower: $(bower -v 2>&1)"
echo "gradle: $(gradle -v 2>&1 | awk '/Gradle/ {print $2}')"
echo "python3.9: $(python3.9 --version 2>&1 | awk '{print $2}')"
echo "pip: $(pip --version | awk '{print $2}')"
echo "pipenv: $(pipenv --version 2>&1)"
echo "poetry: $(poetry --version 2>&1 | awk '{print $3}')"
echo "ruby: $(ruby -v | awk '{print $2}')"
echo "rbenv: $(rbenv -v | awk '{print $2}')"
echo "ruby-build: $(ruby-build --version | awk '{print $2}')"
#echo "go: $(go version | awk '{print $3}')"
#echo "scala: $(scala -version 2>&1 | awk -F ' ' '/version/ {print $4}')"
#echo "sbt: $(sbt sbtVersion 2>&1 | grep '[info] *' | awk '{print $2}')"
#echo "php: $(php -v | head -n 1 | awk '{print $2}')"
#echo "composer: $(composer --version | awk '{print $3}')"
#echo "php plugins: $(php -m)"
#echo "cocoapods: $(pod --version)"
#echo "R: $(R --version | head -n 1 | awk '{print $3}')"
#echo "packrat: $(R -e "packageVersion('packrat')" | grep -o '[0-9]*\.[0-9]*\.[0-9]*')"
#echo "paket: $(mono paket.exe --version)"
#echo "dotnet-sdk: $(dotnet --version)"
#echo "dotnet cli: $(dotnet --list-sdks | tail -1 | awk '{print $1}')"
#echo "nuget: $(nuget help | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*')"
#echo "cargo: $(cargo --version | awk '{print $2}')"a
