#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <aircrack_ufbt_icons.h>

int32_t aircrack_ufbt_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm aircrack_ufbt!");

    return 0;
}
